# Generated by Django 6.0.3 on 2026-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_disease_description_disease_is_emergency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='disease',
            name='specialist',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
