# Generated by Django 6.0.3 on 2026-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_alter_disease_description_alter_disease_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcheck',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
